FROM ubuntu:20.10 as base_stage
# TODO Check for smaller / more fitting linux image

ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}

# Install all build tools & certs for paho etc
RUN apt-get -y update && \
apt-get install -y --no-install-recommends \
git \
cmake \
build-essential --reinstall ca-certificates

FROM base_stage as build_stage
ARG INTEGRATION_TEST_PATH

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Copy C++ SDK sources
COPY /src/sdk/cpp ./src/sdk/cpp

# Copy C++ integration-Test sources
COPY ${INTEGRATION_TEST_PATH} .${INTEGRATION_TEST_PATH}

# set the directory for building the cpp app's
WORKDIR /app${INTEGRATION_TEST_PATH}

# Compile/Build with cmake tools
RUN cmake -B build -S .
RUN cmake --build build --parallel

RUN ls /app${INTEGRATION_TEST_PATH}/build

FROM build_stage as tidy_up_stage

RUN apt-get autoclean && \
apt-get autoremove --purge -y $BUILD_PACKAGES $(apt-mark showauto) && \
rm -rf /var/lib/apt/lists/* 

# TODO for efficiency this runtime layer could be based on alpine for example
FROM tidy_up_stage as runtime_stage

ARG INTEGRATION_TEST_PATH

WORKDIR /app${INTEGRATION_TEST_PATH}/build

CMD ./function_provider_for_test