name: Integration test optimized

on: [push, pull_request]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: Run integration tests

    steps:
    - uses: actions/checkout@v2

    # Testing docker-layer-caching - TODO needs a re-write of docker-compose to have a single .yml file (could use [profiles] for seperation)
    - run: docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Testing a single compose approach (platform + test_suites)
      working-directory: ${{github.workspace}}/docker-compose
      shell: bash
      # Build & run platform.
      # All the SDK's integration tests are dockerized and build the latest version of the platform each time. 
      run: docker-compose -f docker-compose.mosquitto.yml -f docker-compose.platform.yml -f docker-compose.integration_tests_cpp.yml -f docker-compose.integration_tests_cpp.yml -f docker-compose.integration_tests_js.yml -f docker-compose.integration_tests_py.yml --env-file .env up --build -d

    - name: Start test runner
      working-directory: ${{github.workspace}}/docker-compose
      shell: bash
      # This is a test as this container must exit once all tests are completed! The test runner will exit with a 0:pass/1:fail
      run: docker-compose -f docker-compose.integration_tests_runner.yml up --build
      timeout-minutes: 1

